version: 2.1
jobs:
  print_hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Print hello"
          command: "echo Hello!"

  print_world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Print world"
          command: "echo World!"

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
