version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Save string ot text file"
          command: |
            echo "Hello World" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Print out content in file"
          command: |
            cat output.txt

workflows:
  sharing-file-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
