version: 2.1
jobs:
  print_devops_eng_name:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Print Devops Engineer Name"
          command: echo ${DEV_NAME}

workflows:
  say-devops-name-workflow:
    jobs:
      - print_devops_eng_name
