version: 2.1

commands:
  udacity_command:
    docker:
      - image: cimg/base:stable
    commands:
      print_pipeline_id:
        description: "A Simple Command to print pipeline Id"
        parameters:
          pipelineId:
            type: string
            default: $CIRCLE_WORKFLOW_ID
        steps:
          - run: echo << parameters.pipelineId >>

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Save string ot text file"
          command: |
            echo "Hello World" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Print out content in file"
          command: |
            cat output.txt

  print_pipeline_id:
    docker:
      - image: cimg/base:stable
    steps:
      - udacity_command:
          pipelineId: $CIRCLE_WORKFLOW_ID

workflows:
  sharing-file-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_pipeline_id
