version: 2.1

jobs:
  force_a_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Echo a fake env variable"
          command: sudo createdb -h localhost test_db

      - run:
          name: Notify on Fail
          command: echo "This was an intentional Failure"
          when: on_fail

workflows:
  force_error_workflow:
    jobs:
      - force_a_fail
